site_name: Remote Shuffle

repo_name: 'Fork on GitHub '
repo_url: "https://github.com/oap-project/remote-shuffle.git"
edit_uri: ""


nav:
- User Guide: User-Guide.md
- OAP Installation Guide: OAP-Installation-Guide.md
- OAP Developer Guide: OAP-Developer-Guide.md
- Version Selector: "../"



theme: readthedocs


plugins:
  - search
  - mkdocs-versioning:
      version: 1.1.1
      exclude_from_nav: ["image", "js", "css", "fonts", "img"]
